In [1]:
import torch

In [2]:
print("Is CUDA available?")
print(torch.cuda.is_available())

Is CUDA available?
True


In [3]:
device = "cuda" if torch.cuda.is_available() else "cpu"
a = torch.tensor([1, 2, 3, 4, 5], device=device, dtype=torch.float64, requires_grad=True)
b = torch.tensor([0.5, 0.6, 0.7, 0.8, 0.9], device=device, dtype=torch.float64, requires_grad=True)
print("We start with our original data:")
print(a)
print(b)

We start with our original data:
tensor([1., 2., 3., 4., 5.], device='cuda:0', dtype=torch.float64,
       requires_grad=True)
tensor([0.5000, 0.6000, 0.7000, 0.8000, 0.9000], device='cuda:0',
       dtype=torch.float64, requires_grad=True)


In [4]:
transformed_data = torch.mul(a, b).mean()
print("We multiply the two tensors and compute the mean:")
print(transformed_data)

We multiply the two tensors and compute the mean:
tensor(2.3000, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>)


In [5]:
transformed_data.backward()
print('Executed backward propagation.')

Executed backward propagation.


In [6]:
print("Let's examine the gradient:")
print(a.grad)
print(b.grad)

Let's examine the gradient:
tensor([0.1000, 0.1200, 0.1400, 0.1600, 0.1800], device='cuda:0',
       dtype=torch.float64)
tensor([0.2000, 0.4000, 0.6000, 0.8000, 1.0000], device='cuda:0',
       dtype=torch.float64)
